import React from "react";
import OffsetMenu from "./OffsetMenu";
import OffsetSocial from "./OffsetSocial";
import Logo from "./Logo";

class Imprint extends React.Component {

    // COMPONENT DID MOUNT
    componentDidMount() {
        document.title = "Impressum | Sailing Channels";
    }

    // RENDER
	render() {

		return (
            <div className="container">
				<OffsetSocial />
                <Logo />
				<OffsetMenu />
                <div className="row content-row">
					<div className="col-md-3"></div>
					<div className="col-md-6">
	                    <h1 className="content-h1">Imprint</h1>
						<p>
                        The following information (Imprint) is required under German law.</p>

                        <p>Responsible for this site:</p>

                        <p><span className="reverse">nnameggürB samohT</span><br />
                        <span className="reverse">51 eßartsreliewtdiehcS</span><br />
                        <span className="reverse">nlöK 33905</span><br />
                        <span className="reverse">moc.slennahc-gnilias@yoha</span><br />
						</p>

                        <h3>Legal disclaimer</h3>
                        <p>The contents of these pages are generated automatically based on the YouTube channel title, description and videos of the individual channels listed. The creator of this website has no influence on the content of the channel descriptions or other channel related texts. Also, The creator of this website cannot assume liability for the timeless accuracy and completeness of the information. This website contains links to external websites. As the contents of these third-party websites are beyond my control, I cannot accept liability for them. ResponsibiIity for the contents of the linked pages is always held by the provider or operator of the pages.</p>

                        <h3>Data protection</h3>
                        <p>In general, when visiting the website of “Sailing Channels”, no personal data are saved. No data will be passed on to third parties without your consent. We point out that in regard to unsecured data transmission in the internet (e.g. via email), security cannot be guaranteed. Such data could possibIy be accessed by third parties.</p>

                        <h3>Google Analytics</h3>
                        <p>This website uses Google Analytics, a web analytics service provided by Google, Inc. (»Google«). Google Analytics uses cookies, which are text files placed on your computer, to help the website analyze how users use the site. The information generated by the cookie about your use of the website (including your IP address) will be transmitted to and stored by Google on servers in the United States. On this website the IP anonymization feature is activated. As a result Google will truncate/anonymize the last octet of the IP address for Member States of the European Union as well as for other parties to the Agreement on the European Economic Area. Only in exceptional cases, the full IP address is sent to and shortened by Google servers in the USA. On behalf of the website provider Google will use this information for the purpose of evaluating your use of the website, compiling reports on website activity for website operators and providing other services relating to website activity and internet usage to the website provider. Google will not associate your IP address with any other data held by Google. By using this website, you consent to the processing of data about you by Google in the manner and for the purposes set out above.</p>

                        <h4>How to prevent being tracked by Google Analytics on sailing-channels.com</h4>

                        <ul>
                            <li>You may refuse the use of cookies by selecting the appropriate settings on your browser. However, please note that if you do this, you may not be able to use the full functionality of this website.</li>
                            <li>Furthermore you can prevent Google’s collection and use of data (cookies and IP address) by downloading and installing the browser plug-in available under <a href="https://tools.google.com/dlpage/gaoptout?hl=en" target="_blank">https://tools.google.com/dlpage/gaoptout?hl=en</a></li>
                        </ul>
					</div>
					<div className="col-md-3"></div>
                </div>
            </div>
		);
	}
}

export default Imprint;
